version: "3.8"
services: 
  postgres:
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=wild_oasis
    ports:
      - "5439:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data
  be: 
    build: 
      context: ./be
      dockerfile: dockerfile.dev
    ports:
      - "3000:3000"
    env_file:
      - ./be/.env 
    depends_on:
      - postgres
    volumes:
      - ./be:/app

  fe:
    build:
      context: ./fe
      dockerfile: dockerfile.dev
    ports:
    - "4000:4000"
    env_file:
      - ./fe/.env
    volumes:
      - ./fe:/app
      - /app/node_modules


volumes:
  pgdata-dev:
  