FROM node:22-alpine AS build

WORKDIR /app

COPY package.json .

RUN npm cache clean --force

RUN npm install

COPY . .

RUN npm run build

# ------------------------------------------------------------
FROM node:22-alpine AS production

WORKDIR /app

# Copy built files from the build stage
COPY --from=build /app/public ./public
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static

ENV NODE_ENV=production

EXPOSE 4000

CMD ["node", "server.js"]

