FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache postgresql-client

ENV IS_PRODUCTION=false

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN chmod +x /app/entrypoint-dev.sh

ENTRYPOINT [ "/app/entrypoint-dev.sh" ]